SEQ_NUMERIC_DISTANCE = 3
SEQ_STRING_FRAC_DISTANCE = 0.4
SEQ_FUZZY_SEARCH_FRAC_DISTANCE = 0.3

DATA_MODEL_BLOCK_LINE_ALIGNMENT = 9
DATA_MODEL_LINE_RIGHT_CHAR = 3
DATA_MODEL_LINE_NEXT_LINE = 0.7

FUZZY_SEARCH_CASE_MISMATCH_COST = 0.1
